default world host {
  import host-exec: func(cmd: string, args: list<string>) -> (exit-code: s32, message: string)
  import host-openai: func(prompt: string) -> (exit-code: s32, message: string)
  import host-loading: func(loading: bool)
  import host-select: func(options: list<string>) -> option<string>

  export run: func()
}